name: munchkinhalfling/bettermake
sourceType: git
source: git://github.com/munchkinhalfling/bettermake
scripts:
  build:
    - ./configure --prefix=$(PREFIX)
    - make
  install:
    - make install OPTDIR=$(PREFIX)/utils
bin:
  bettermake: bin/bettermake
  mk-command: utils/mk-command
  mk-header: utils/mk-header
  mk-detail: utils/mk-detail